POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Heres another test",
    "important": true,
    "userId": "673394b611596f062b18f68f"
}

###
GET http://localhost:3001/api/notes